### ISSUE TITLE
filter needs to accept routed parameters 

### ISSUE THREAD

**Issue by pukeko37** [danielSanchezQ/warp-reverse-proxy#10]
I want to build a reverse proxy that determines the proxy address dynamically for each connection request, rather than using a hard-coded parameter that remains fixed for all invocations.

I struggled long and hard trying to make work / re-build your reverse_proxy_filter function to be async and accept routed parameters, but sadly my knowledge of warp isn't up to it.

So, my suggestion is, to be generally useful, your filter needs to accept routed parameters [or provide an example that shows warp newbies like me how to configure a route to accept routed parameters]

**Comment by danielSanchezQ** [comment]
@pukeko37 Would you please make an example of what would be the approximated API?

**Comment by pukeko37** [comment]
Sure, I'll put an example together to show you what I mean.

**Comment by pukeko37** [comment]
I would imagine the signature would look something like this:

```
async fn reverse_proxy_filter(
    base_path: String,
    proxy_address: String,
) -> Result<impl warp::Reply, Rejection> {..
}
```

Although in my case, I'm not sure of the value of having `base_path`. I think perhaps your library users could manage the base path themselves, or perhaps you could provide a separate helper function.

Also, I think using a specific domain type for the proxy address (such as `http::uri::Uri` or `std::net::IpAddr` instead of `String` would make the interface better by taking advantage of rust's type system.

So, I can think of several use cases for a dynamic proxy address that can change for each web request:
- As a round-robin load-balancer that can distribute web requests across several target servers
- As an authenticating server (such as OAuth server) that determines the target server from the authentication token (e.g. from the `aud:` field),
- To rewrite the url, and pass the web request to different target servers, depending on query parameters (say), 
- To distribute the traffic to separate servers (CQRS style) depending on request method (so that GETs go to a read-only server, and POST, DELETE, etc go to an update server),
- etc, etc...

Here I have a round-robin load balancer example: 
I have a list of target servers: `target_vec`, that I cycle through by calling next_target

```
async fn next_target(target: Arc<Mutex<Targets<'_>>>) -> Result<String, Infallible> {
    let mut targets = target.lock().await;
    Ok(format!("http://{}", targets.next().unwrap()))
}
```

I set up my targets in once at the start:
```
#[tokio::main]
async fn main() {
    let target_vec: Targets = get_targets("MyApp").unwrap().iter().cycle();
    let target = Arc::new(Mutex::new(target_vec.clone()));
    let target = warp::any().map(move || Arc::clone(&target));
    // println!("next: {}", next_target(target).await);
    println!("targets: {:?}", &target_vec);
```

And then I have a warp route that looks something like this:

```
let app = warp::path!("hello" / ..)
        .map(|| "/".to_string()) // base parameter
        .and((target.clone()).and_then(next_target)) // proxy target address
        .and(reverse_proxy_filter);
// spawn proxy server
    warp::serve(app).run((CONFIG.ip, CONFIG.port)).await;
}
```

**Comment by pukeko37** [comment]
I thought I'd give you some clean working code using a dummy `reverse_proxy_filter1` to show the API.

When you repeatedly run` http://127.0.0.1:8000/hello`  in a browser, it outputs the this in a cycle:
```
Some output: /, http://127.0.0.1:3030
Some output: /, http://127.0.0.1:3031
Some output: /, http://127.0.0.1:3030
Some output: /, http://127.0.0.1:3031
[...]
```

```
use std::convert::Infallible;
use std::net::SocketAddr;
use std::net::{IpAddr, Ipv4Addr};
use std::str::FromStr;
use std::sync::Arc;
use tokio::runtime::Runtime;
use tokio::sync::Mutex;
use warp::{Filter, Rejection};

type Targets = std::iter::Cycle<std::vec::IntoIter<std::net::SocketAddr>>;

pub fn get_targets() -> Vec<std::net::SocketAddr> {
    let mut targets: Vec<std::net::SocketAddr> = Vec::new();
    targets.push(SocketAddr::new(
        IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)),
        3030,
    ));
    targets.push(SocketAddr::new(
        IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)),
        3031,
    ));
    targets
}

async fn next_target(target: Arc<Mutex<Targets>>) -> Result<String, Infallible> {
    let mut targets = target.lock().await;
    let target = targets.next().unwrap();
    Ok(format!("http://{}", target))
}

async fn reverse_proxy_filter1(
    base_path: String,
    proxy_address: String,
) -> Result<impl warp::Reply, Rejection> {
    Ok(format!("Some output: {}, {}", base_path, proxy_address))
}

fn main() {
    let target_vec: Targets = get_targets().into_iter().cycle();
    println!("targets: {:?}", &target_vec);
    let tg = Arc::new(Mutex::new(target_vec.clone()));
    let target = warp::any().map(move || Arc::clone(&tg));

    let mut rt = Runtime::new().unwrap();

    rt.block_on(async {
        let app = warp::path!("hello" / ..)
            .map(|| "/".to_string())
            .and((target).and_then(next_target))
            .and_then(reverse_proxy_filter1);
        warp::serve(app)
            .run((IpAddr::from_str("127.0.0.1").unwrap(), 8000))
            .await;
    });
}
```

**Comment by danielSanchezQ** [comment]
@pukeko37 Thanks for the effort!

> Also, I think using a specific domain type for the proxy address (such as http::uri::Uri or std::net::IpAddr instead of String would make the interface better by taking advantage of rust's type system.

Indeed, and it is something I had in mind. Definitely will be done.

Related to use the parameters as filters:

It looks interesting, but I have to think about the best way of doing this. Maybe the simplest way would be to receive another filter that extracts both `base_path` and `proxy_address`. Or just a function would be enough. I'll give it a try and be back with what I find.

**Comment by danielSanchezQ** [comment]
@pukeko37 

After trying different APIs for this. I like the one in this [draft](https://github.com/danielSanchezQ/warp-reverse-proxy/pull/14). Basically, the builder method requires another two boxed filters that would provide the required data.
Please take a look and give me feedback. I can adapt your example with this new API too if it is helpful.

Thanks!

**Comment by pukeko37** [comment]
@danielSanchezQ 

Yes, well, maybe. Not sure this solves the problem... Trouble is, I'm not confident enough about warp to know whether or how this might work.

Suppose we want to handle: `POST hello/:port`, And we want to create a route that will extract the port number from the path and construct the new boxed `proxy_address_filter`. How would we do that?

```
let app = warp::path!("hello" / String)
    .map(|port| {       // to construct the proxy address
        format!("http://127.0.0.1:8080/:{}", port)
    }). [... // magic here!]
.reverse_proxy_filter(base_path_filter, proxy_address_filter)
```
How do we get the proxy address into the new boxed proxy_address_filter?

**Comment by danielSanchezQ** [comment]
@pukeko37 I see. I did not want to lose control over the filter and I don't want to complicate the API too much. It should be simple. But, I see that for being flexible it would need to. So, the solution here is to expose the forwarding method and the request filter (which is already public). And let the people compose them.
I'll think about the options.

**Comment by danielSanchezQ** [comment]
@pukeko37 Would this work for your example?

```rust
#[tokio::main]
async fn main() {
    let hello = warp::path!("hello" / String).map(|name| format!("Hello, {}!", name));

    // // spawn base server
    tokio::spawn(warp::serve(hello).run(([0, 0, 0, 0], 8080)));

    let request_filter = extract_request_data_filter();
    let app = warp::path!("hello" / String)
        .map(|port| (format!("http://127.0.0.1:{}/", port), "".to_string()))
        .untuple_one()
        .and(request_filter)
        .and_then(proxy_to_and_forward_response)
        .and_then(log_response);

    // spawn proxy server
    warp::serve(app).run(([0, 0, 0, 0], 3030)).await;
}
```

I'm thinking about letting the preloaded simple proxy filter, but make public the function that handles proxying so more complicated things can be done. 
The above example is working.

**Comment by pukeko37** [comment]
Yes, that looks good.

Not sure what `.untuple_one()` is doing (why you need it), and I'll have to check out extract_request_data_filter, But at first look, it seems like it fits the bill.

**Comment by danielSanchezQ** [comment]
@pukeko37 let me know if you can experiment with [this](https://github.com/danielSanchezQ/warp-reverse-proxy/pull/15) what is your opinion.

`untuple_one` is used to un-pack filter results, so for example, if you have 2 filters that extracts `(i32, i32)` and `(u32, u32)` by combining them you would get `((i32, i32), (u32, u32))`, but if you use `untuple` for each of them you would flatten that into `(i32, i32, u32, u32)`. So in that case `proxy_to_and_forward_response` needs to receive the parameters flatten hence I untuple the results from the `.map(|port| (format!("http://127.0.0.1:{}/", port), "".to_string()))` call.

**Comment by pukeko37** [comment]
Hi Daniel,

I will have a play with the new changes. But won't be for a week or two, now.

Yes I understand what flatten is for, but my problem is why is it needed here? the .map () will consume the original port(string) and replace it with a tuple which contains the full uri string. Isn't it already as flat as it can get?

Or am I missing something?

Cheers,
Andrew

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielSanchezQ** [comment]
@pukeko37 I think you are missing the `extract_request` request filter which itself extracts another tuple. Which by composing with the previous filter will give us some nested tuples like `((String, String), (Request, Fields, ...))` when we actually want `(String, String, Request, Fields, ...)` because that is what is expected for the `proxy_to_and_forward_response` to take as arguments.

**Comment by danielSanchezQ** [comment]
This was featured in #15
