### ISSUE TITLE
Pass context down

### ISSUE THREAD

**Issue by juliotpaez** [danielSanchezQ/warp-reverse-proxy#35]
Hello,

I think it would be very useful to include a generic parameter in the `proxy_to_and_forward_response` to pass a shared context down the pipeline.

My case is that I want to log the bytes moved to backends (this is ok) but also from them (this is not because I can pass info through `proxy_to_and_forward_response`).

I can make a PR to help you.

**Comment by danielSanchezQ** [comment]
Hi Julio!

I would like to know if there is any other way of doing that. This change probably would imply a change on API and I would like to be sure it is needed.
Can't you impose something like? :
```rust, ignore
 let request_filter = extract_request_data_filter();
 let app = warp::path!("hello" / String)
     .map(|port| (format!("http://127.0.0.1:{}/", port), "".to_string()))
     .untuple_one()
     .and(request_filter)
     .and_then(proxy_to_and_forward_response)
     .and_then(log_response);
 ```

**Comment by juliotpaez** [comment]
Hi Daniel,

I'm using that approach but it is not clear how to pass a DB or Context object for example to `log_response`.

The "best" approach I can see right now to not break the API is this:

```rust
// Add this new method, which is just copy-paste of proxy_to_and_forward_response but with a generic.
pub async fn proxy_to_and_forward_response_with_context<T>(
    context: T,
    proxy_address: String,
    base_path: String,
    uri: FullPath,
    params: QueryParameters,
    method: Method,
    headers: HeaderMap,
    body: Bytes,
) -> Result<(T, http::Response<Bytes>), Rejection> {
    let proxy_uri = remove_relative_path(&uri, base_path, proxy_address);
    let request = filtered_data_to_request(proxy_uri, (uri, params, method, headers, body))
        .map_err(warp::reject::custom)?;
    let response = proxy_request(request).await.map_err(warp::reject::custom)?;

    match response_to_reply(response)
        .await
        .map_err(warp::reject::custom)
    {
        Ok(response) => Ok((context, response)),
        Err(e) => Err(e),
    }
}

// Then, modify this method to use the above.
pub async fn proxy_to_and_forward_response(
    proxy_address: String,
    base_path: String,
    uri: FullPath,
    params: QueryParameters,
    method: Method,
    headers: HeaderMap,
    body: Bytes,
) -> Result<http::Response<Bytes>, Rejection> {
    match proxy_to_and_forward_response_with_context(
        (),
        proxy_address,
        base_path,
        uri,
        params,
        method,
        headers,
        body,
    )
    .await
    {
        Ok(v) => Ok(v.1),
        Err(e) => Err(e),
    }
}
```

What do you think about this solution?

**Comment by danielSanchezQ** [comment]
Let me think about this for a bit. I see the problem here. It may be worth the version update.
I just want to check the best way of doing this.
Thanks!

**Comment by juliotpaez** [comment]
Oh sorry I just realize that the `proxy_to_and_forward_response` method is public, so I can call it from inside my method.

Like this:
```rust
 let request_filter = extract_request_data_filter();
 let app = warp::path!("hello" / String)
     // ... get data ...
     .and_then(/* my method that calls proxy_to_and_forward_response */)
     // ... next actions ...
```

I think the previous solution I gave you could be useful for a new version maybe. Also an example with something like that will be helpfull in the future.

Anyway, sorry to disrupt you and thanks.

**Comment by danielSanchezQ** [comment]
@juliotpaez No disruption at all. You opened a new path here. I'll consider adding that solution for the next release. Thanks for it!
Please, feel free (actually I would love it) to open a PR with the example of how you solved the problem.

**Comment by juliotpaez** [comment]
Ok, I'll post it as soon as I get it working.
