### ISSUE TITLE
Feature request: option to customize the reqwest client

### ISSUE THREAD

**Issue by jtroo** [danielSanchezQ/warp-reverse-proxy#44]
The warp-reverse-proxy library uses reqwest behind the scenes but it is currently not possible to customize the reqwest client configuration.

There are some use cases where client configs other than the default are needed, so it would be good provide this functionality.

**Comment by danielSanchezQ** [comment]
@jtroo, would you mind check if #45 would suit your needs? 
Any other suggestion is welcome :)

**Comment by jtroo** [comment]
Gave it a try, looks good to me!

**Comment by jtroo** [comment]
One potential improvement regarding the test would be that you could force serialized testing in the Rust code, so that anyone running `cargo test` without forcing a single thread of execution can get a consistent result.

The crate I personally use for this is [serial_test](https://crates.io/crates/serial_test).

**Comment by danielSanchezQ** [comment]
Nice to know about serial. But tests should be consistent anyway now. I didn't enforced the single thread in the end even if the commit, indeed, exists.
Thanks for your feedback!

**Comment by danielSanchezQ** [comment]
Implemented in #45
