### ISSUE TITLE
Add feature fast cgi client

### ISSUE THREAD

**Issue by git001** [danielSanchezQ/warp-reverse-proxy#65]
Maybe it could be interesting to add the possibility to make request to a Fast CGI server.

This library looks quite nice and easy to use as I have use it for my small [fastcgi-healthcheck](https://github.com/git001/fastcgi-healthcheck)  
https://github.com/Icelk/fastcgi-client-rs

**Comment by danielSanchezQ** [comment]
> Maybe it could be interesting to add the possibility to make request to a Fast CGI server.
> 
> This library looks quite nice and easy to use as I have use it for my small [fastcgi-healthcheck](https://github.com/git001/fastcgi-healthcheck) https://github.com/Icelk/fastcgi-client-rs

Uhm, well, atm it just works with http/s interfaces, but it may be ok to abstract the connection. Although I would have to think if it would go out of the scope of the filter. Maybe we could add a feature gated expansion to add socket connections.
Would you be interested in giving it a try?

**Comment by git001** [comment]
Well I will need some time for that as rust is very new language for me.

**Comment by danielSanchezQ** [comment]
> Well I will need some time for that as rust is very new language for me.

I could guide you. But it is definitely not an easy task, because we would need to create a client that holds and handle the connections.  I do not have the bandwidth for dealing with this. Also I was thinking it could be a separated crate (that reuses some of the utilities in this one).

**Comment by git001** [comment]
Okay, thanks for your offer.
I can close this issue if you want and open it when I think I'm ready or do you want to keep it open?

**Comment by danielSanchezQ** [comment]
> Okay, thanks for your offer. I can close this issue if you want and open it when I think I'm ready or do you want to keep it open?

Better to close for now then, yes. Thanks!

**Comment by git001** [comment]
Maybe it will be implemented in the future.
